// GERADO por scripts/gerar-carteira.mjs — NÃO editar à mão (exceto OCULTOS, abaixo).
// Fonte: site-antigo-clientes.html, a antiga página pública de clientes da agência.
// Regenerar: node scripts/gerar-carteira.mjs   (não roda no build)
//
// 257 nomes, já deduplicados. A página /clientes une esta lista com
// content/clientes.ts (a grade de cima) — quem já aparece lá em cima não repete aqui
// embaixo, e quem existe SÓ no clientes.ts continua aparecendo. Nunca substituição.

export interface ClienteCarteira {
  /** Nome como a agência já publicou, sem reescrita. */
  nome: string;
  /** Área primária — o eixo do agrupamento na página. */
  area: string;
  cidade: string;
  uf: string;
  /** Clínica · Médico · Hospital · Laboratório · Associação · Evento · Serviços · Website */
  tipo: string;
}

// Nome que sai da página: ADICIONE a linha aqui — nunca apague a linha do registro
// lá embaixo. O razão fica completo e o motivo do corte fica visível no diff.
// O gerador relê esta lista e a reescreve intacta a cada run.
export const OCULTOS: string[] = [];

export const CARTEIRA: ClienteCarteira[] = [
  { nome: "Agcare – Hotelaria Assistida e Cuidado Integral", area: "Saúde Integrativa", cidade: "São Paulo", uf: "SP", tipo: "Clínica" },
  { nome: "Ampla Drogaria Especializada", area: "Farmácia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Angiomedi – Centro Integrado de Angiologia", area: "Medicina Especializada", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "AngioPlace – Excelência Vascular e Laser", area: "Medicina Especializada", cidade: "Goiânia", uf: "GO", tipo: "Clínica" },
  { nome: "Associação Psiquiátrica de Brasília – APBr", area: "Psiquiatria", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Atennuar – Clínica de alívio da dor e cirurgia Bucomaxilofacial", area: "Medicina Especializada", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Bem Estar", area: "Laboratório", cidade: "Mineiros", uf: "GO", tipo: "Clínica" },
  { nome: "Benedik – Cirurgia Plástica e Estética Facial", area: "Cirurgia Plástica", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Bonvena – Medicina Reprodutiva e Centro de referência em Endometriose", area: "Medicina Reprodutiva", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Brasília Otoclínica – Otorrinolaringologia", area: "Otorrinolaringologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "CAMF – Diagnóstico por Imagens e Medicina Fetal", area: "Diagnóstico Médico", cidade: "Araçatuba", uf: "SP", tipo: "Clínica" },
  { nome: "Cardio Clinic", area: "Cardiologia", cidade: "Parauapebas", uf: "PA", tipo: "Clínica" },
  { nome: "Cardiolago – Instituto de Cardiologia do Lago", area: "Cardiologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Casa de Saúde de Remanso", area: "Saúde Geral", cidade: "Remanso", uf: "BA", tipo: "Hospital" },
  { nome: "CBCOR – Centro Brasileiro Cardiovascular", area: "Cardiologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "CDUS – Medicina de Precisão", area: "Diagnóstico Médico", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Centro Clínico Iturama", area: "Saúde Geral", cidade: "Iturama", uf: "MG", tipo: "Clínica" },
  { nome: "Centro Clínico – Saúde Agora", area: "Saúde Geral", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Centro de Beleza Daher", area: "Dermatologia e Estética", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "CentroMeb – Centro Médico Brasília", area: "Medicina Especializada", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Centro Médico Navegantes", area: "Saúde Geral", cidade: "Rio de Janeiro", uf: "RJ", tipo: "Clínica" },
  { nome: "Centro Ortopédico de Taguatinga", area: "Ortopedia", cidade: "Taguatinga", uf: "DF", tipo: "Clínica" },
  { nome: "Centrus – Diagnóstico por imagem", area: "Diagnóstico Médico", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "CETFISIO – Fisioterapia e Bem-estar no Gama", area: "Ortopedia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Cisma – Centro Integrado da Saúde Macedo", area: "Odontologia", cidade: "Rio Verde", uf: "GO", tipo: "Clínica" },
  { nome: "CLIAOD – Otorrinolaringologia", area: "Otorrinolaringologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Climepa Medicina Ocupacional", area: "Saúde Ocupacional", cidade: "Parauapebas", uf: "PA", tipo: "Clínica" },
  { nome: "Clínica Appia", area: "Dermatologia e Estética", cidade: "Rio de Janeiro", uf: "RJ", tipo: "Clínica" },
  { nome: "Clínica BabyPed", area: "Pediatria", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica CAPELLI Bauru – Transplante Capilar", area: "Dermatologia e Estética", cidade: "Bauru", uf: "SP", tipo: "Clínica" },
  { nome: "Clínica Carvalho – Medicina e Saúde", area: "Saúde Geral", cidade: "Piracicaba", uf: "SP", tipo: "Clínica" },
  { nome: "Clínica Cirúrgica Taguatinga", area: "Medicina Especializada", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica Dal Bello", area: "Dermatologia e Estética", cidade: "Caxias do Sul", uf: "RS", tipo: "Clínica" },
  { nome: "Clínica de Otorrino da Asa Norte", area: "Otorrinolaringologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica de Veias – Diagnóstico e tratamento de Doenças Vasculares", area: "Medicina Especializada", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica Dimas Dutra", area: "Odontologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica Donna", area: "Saúde da Mulher", cidade: "Paracatu", uf: "MG", tipo: "Clínica" },
  { nome: "Clínica do Rim e Hipertensão", area: "Nefrologia", cidade: "Valparaíso de Goiás", uf: "GO", tipo: "Clínica" },
  { nome: "Clínica Evexia", area: "Dermatologia e Estética", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica Humanas – Medicina e Reabilitação", area: "Fonoaudiologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica Inspire", area: "Saúde Geral", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica IOT", area: "Ortopedia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica Janice Lamas Radiologia", area: "Diagnóstico Médico", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica Lúmina", area: "Saúde da Mulher", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica NutroMaster – Nutrologia Médica e Endocrinologia", area: "Endocrinologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica Reju – Excelência Vascular", area: "Medicina Vascular", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica Renovare – Urologia e Andrologia", area: "Urologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica Santa Maria Auxiliadora", area: "Saúde Geral", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica Santo Antônio – Policlínica", area: "Neurologia", cidade: "Espírito Santo", uf: "ES", tipo: "Clínica" },
  { nome: "Clínica São Camilo", area: "Saúde Geral", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Clínica Sponte & Bedenken – Psiquiatria e Psicologia", area: "Psiquiatria", cidade: "São Paulo", uf: "SP", tipo: "Clínica" },
  { nome: "Clínica Vacine", area: "Saúde Preventiva", cidade: "Parauapebas", uf: "PA", tipo: "Clínica" },
  { nome: "Clínica VivaVita", area: "Saúde Geral", cidade: "Pindamonhangaba", uf: "SP", tipo: "Clínica" },
  { nome: "CM – Dra. Cláudia Vasconcelos – Pediatria e Neonatologia", area: "Pediatria", cidade: "Tucuruí", uf: "PA", tipo: "Médico" },
  { nome: "CMT – Centro Médico de Taguatinga", area: "Medicina Especializada", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Com Saúde – Centro Médico", area: "Saúde Geral", cidade: "Aracaju", uf: "SE", tipo: "Clínica" },
  { nome: "CON – Clínica Oncologia Hematologia", area: "Oncologia", cidade: "Rio de Janeiro", uf: "RJ", tipo: "Clínica" },
  { nome: "CORE Cardiologia", area: "Cardiologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Costa Daher Clínica", area: "Cirurgia Plástica", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "CPAPS Terapia do Sono", area: "Medicina Especializada", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "CRMB – Centro de Reconstrução Mamária de Brasília", area: "Cirurgia Plástica", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Daher Hospital Lago Sul", area: "Saúde Geral", cidade: "Brasília", uf: "DF", tipo: "Hospital" },
  { nome: "DAMA Centro Médico", area: "Medicina Especializada", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Dedicae – Ginecologia e Dermatologia", area: "Saúde da Mulher", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Di Lamartine – Cirurgia Plástica", area: "Cirurgia Plástica", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Dra. Aline Mello", area: "Diagnóstico Médico", cidade: "Ceres", uf: "GO", tipo: "Médico" },
  { nome: "Dra. Ana Cristina Medanha", area: "Medicina da Dor", cidade: "Araguaína", uf: "TO", tipo: "Médico" },
  { nome: "Dra. Ana Lobbo", area: "Dermatologia e Estética", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dra. Antoniele Bezerra Navarro", area: "Cardiologia", cidade: "Recife", uf: "PE", tipo: "Médico" },
  { nome: "Dra. Cíntia Chaves", area: "Geriatria", cidade: "Porto Velho", uf: "RO", tipo: "Médico" },
  { nome: "Dra. Daniela Machado", area: "Dermatologia e Estética", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dra. Daniele Pollo – Oftalmologista", area: "Oftalmologia", cidade: "Parauapebas", uf: "PA", tipo: "Médico" },
  { nome: "Dra. Danielly Ambrosio Borges – Pediatra", area: "Pediatria", cidade: "São Paulo", uf: "SP", tipo: "Médico" },
  { nome: "Dra. Fabyanne Mazutti", area: "Endoscopia Ginecológica", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dra. Flávia Loyola – Geriatra", area: "Geriatria", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Dra. Janina Huguenin", area: "Oncologia Cirúrgica", cidade: "Rio de Janeiro", uf: "RJ", tipo: "Médico" },
  { nome: "Dra. Júlia Medeiros", area: "Medicina Vascular", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Dra. Laís Bulsoni", area: "Mastologia", cidade: "Porto Velho", uf: "RO", tipo: "Médico" },
  { nome: "Dra. Letícia Moraes", area: "Medicina Especializada", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Alfonso Soria", area: "Ortopedia", cidade: "Porto Alegre", uf: "RS", tipo: "Médico" },
  { nome: "Dr. Allan Garcia", area: "Ortopedia", cidade: "Vitória", uf: "ES", tipo: "Médico" },
  { nome: "Dr. Alysson Zanatta", area: "Saúde da Mulher", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dra. Marcela Cammarota", area: "Cirurgia Plástica", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dra. Marcela de Brito", area: "Ginecologia", cidade: "Patrocínio", uf: "MG", tipo: "Médico" },
  { nome: "Dra. Marcela De Caroli", area: "Medicina Vascular", cidade: "São Paulo", uf: "SP", tipo: "Médico" },
  { nome: "Dra. Marcia Maria Barros Moreira", area: "Cirurgia Plástica", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dra. Maria Eduarda Amaral", area: "Saúde da Mulher", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dra. Mariana Alcantara", area: "Cirurgia Plástica", cidade: "São Paulo", uf: "SP", tipo: "Médico" },
  { nome: "Dra. Maysa Araujo Melo", area: "Endocrinologia", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Dra. Mirian Helena Hoeschl Abreu", area: "Saúde da Mulher", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dra. Natália Tibúrcio de Araújo", area: "Cirurgia", cidade: "São Paulo", uf: "SP", tipo: "Médico" },
  { nome: "Dra. Nilse Querino – Infectologista", area: "Infectologia", cidade: "Salvador", uf: "BA", tipo: "Médico" },
  { nome: "Dr. Antonio Carlos de Souza", area: "Medicina Especializada", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dra. Patrícia Andréia Rodrigues Ferreira – Dermatologista", area: "Dermatologia e Estética", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Dra. Rayane Cardoso – Cirurgia Oncológica e Laparoscópica", area: "Oncologia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dra. Rayssa Lucena", area: "Nutrição e Bem-Estar", cidade: "Fortaleza", uf: "CE", tipo: "Médico" },
  { nome: "Dra. Rhaiana Gondim – Urologia e Uropediatria", area: "Urologia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Arnaldo Porto", area: "Cardiologia", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Dr. Auricelio Batista Cezar Júnior", area: "Medicina Especializada", cidade: "Recife", uf: "PE", tipo: "Médico" },
  { nome: "Dr. Bráulio Moraes", area: "Urologia", cidade: "Guaxupé", uf: "MG", tipo: "Médico" },
  { nome: "Dr. Bruno Lorenção", area: "Medicina Vascular", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Carlos Magno", area: "Cirurgia Geral", cidade: "Uruaçu", uf: "GO", tipo: "Médico" },
  { nome: "Dr. Carlos Portocarrero", area: "Saúde da Mulher", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Celso Melo – Nutrólogo", area: "Medicina Especializada", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Claúdio Costa – Ortopedia e Cirurgia da Coluna", area: "Ortopedia", cidade: "Recife", uf: "PE", tipo: "Médico" },
  { nome: "Dr. Clenio Fonseca – Oftalmologista", area: "Oftalmologia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Cristóvão Neto – Urologista", area: "Urologia", cidade: "São Paulo", uf: "SP", tipo: "Médico" },
  { nome: "Dr. Davi Heckmann", area: "Medicina Vascular", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Douglas Pigosso", area: "Oftalmologia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Douglas Ribeiro – Otorrinolaringologista", area: "Otorrinolaringologia", cidade: "São Paulo", uf: "SP", tipo: "Médico" },
  { nome: "Dr. Eder Nisi Ilario – Urologista/Uro-oncologista", area: "Urologia", cidade: "São Paulo", uf: "SP", tipo: "Médico" },
  { nome: "Dr. Eduardo Medeiros", area: "Ortopedia", cidade: "Mossoró", uf: "RN", tipo: "Médico" },
  { nome: "Dr. Felipe Antônio Ruy Buarque", area: "Oncologia", cidade: "Rio de Janeiro", uf: "RJ", tipo: "Médico" },
  { nome: "Dr. Felipe Mendonça", area: "Medicina Vascular", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Dr. Fernando Prudente – Ortopedista", area: "Ortopedia", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Dr. Flávio Braga", area: "Cardiologia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Flávio Viana Aleixo", area: "Neurologia", cidade: "Rio Verde", uf: "GO", tipo: "Médico" },
  { nome: "Dr. Francisco José de Carvalho", area: "Ortopedia", cidade: "Vitória", uf: "ES", tipo: "Médico" },
  { nome: "Dr. Gabriel Bijos", area: "Cirurgia Plástica", cidade: "São José dos Campos", uf: "SP", tipo: "Médico" },
  { nome: "Dr. Gabriel Imperial", area: "Urologia", cidade: "Ceres", uf: "GO", tipo: "Médico" },
  { nome: "Dr. Gilvan Furtado", area: "Urologia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Heder Murari Borba", area: "Urologia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Heitor Garcia", area: "Cirurgia Plástica", cidade: "Iturama", uf: "MG", tipo: "Médico" },
  { nome: "Dr. Hélio Mota", area: "Medicina da Dor", cidade: "Salvador", uf: "BA", tipo: "Médico" },
  { nome: "Dr. Homero Ribeiro", area: "Urologia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Jessé Lima", area: "Cirurgia Plástica", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Joao Marcos Ibrahim", area: "Urologia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. José Antonio Jatene", area: "Cardiologia", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Dr. José Carlos Daher", area: "Cirurgia Plástica", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Leonardo Vieira", area: "Gastroenterologia", cidade: "Lucas do Rio Verde", uf: "MT", tipo: "Médico" },
  { nome: "Dr. Luciano Morais", area: "Medicina Vascular", cidade: "São Paulo", uf: "SP", tipo: "Médico" },
  { nome: "Dr. Luís Gustavo Hernandes", area: "Medicina Vascular", cidade: "Piracicaba", uf: "SP", tipo: "Médico" },
  { nome: "Dr. Luis Henrique Rigon", area: "Oncologia", cidade: "Rio de Janeiro", uf: "RJ", tipo: "Médico" },
  { nome: "Dr. Luís Kléber Fernandes", area: "Urologia", cidade: "Uruaçu", uf: "GO", tipo: "Médico" },
  { nome: "Dr. Manoel Ribeiro Jr", area: "Oftalmologia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Márcio Silveira", area: "Ortopedia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Marcos Rolim", area: "Saúde Geral", cidade: "Cacoal", uf: "RO", tipo: "Médico" },
  { nome: "Dr. Mohamad Omairi", area: "Cirurgia Geral", cidade: "Foz do Iguaçu", uf: "PR", tipo: "Médico" },
  { nome: "Dr. Murilo Almeida", area: "Ortopedia", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Dr. Nathan Guastalli", area: "Medicina Esportiva", cidade: "Campinas", uf: "SP", tipo: "Médico" },
  { nome: "Dr. Ocimar Trindade – Cirurgia Plástica", area: "Cirurgia Plástica", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Osei Akuamoa Júnior – Urologia e Andrologia", area: "Urologia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Paulo Corá – Ortopedia e Medicina da Dor", area: "Ortopedia", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Dr. Pedro Rosa – Ginecologia e Obstetrícia, Histeroscopia e Reprodução Humana", area: "Saúde da Mulher", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Pedro Tolentino – Cirurgia de Cabeça e Pescoço", area: "Cirurgia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Philipe Sena", area: "Saúde Geral", cidade: "Porto Seguro", uf: "BA", tipo: "Médico" },
  { nome: "Dr. Pottyer Vieira – Psiquiatra", area: "Psiquiatria", cidade: "Porto Velho", uf: "RO", tipo: "Médico" },
  { nome: "Dr. Rafael Quaresma – Cirurgia Plástica", area: "Cirurgia Plástica", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Ramon Teles – Otorrinolaringologia e Cirurgia Craniomaxilofacial", area: "Otorrinolaringologia", cidade: "Crato", uf: "CE", tipo: "Médico" },
  { nome: "Dr. Raul Carlos Barbosa – Ortopedista e Traumatologista, Cirurgia do Pé e Tornozelo", area: "Ortopedia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Renan R. Marangoni – Cirurgia do Aparelho Digestivo, Cirurgia Geral", area: "Cirurgia", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Dr. Rodolfo Bertoldo – Cirurgia do Aparelho Digestivo e Coloproctologia", area: "Cirurgia", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Dr. Rodolpho Lemes – Ortopedia e Traumatologia", area: "Ortopedia", cidade: "Uruaçu, Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Dr. Rodrigo Petros – Ortopedista e Traumatologista, Ombro e Cotovelo", area: "Ortopedia", cidade: "Rio de Janeiro", uf: "RJ", tipo: "Médico" },
  { nome: "Dr. Rodrigo Villalva – Urologia, Andrologia e Cirurgia Robótica", area: "Urologia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Silvio Holenbach – Otorrinolaringologista", area: "Otorrinolaringologia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Dr. Tárik Jabour – Psiquiatra", area: "Psiquiatria", cidade: "Juiz de Fora", uf: "MG", tipo: "Médico" },
  { nome: "Dr. Thiago Becker – Cirurgia Gástrica e Bariátrica", area: "Cirurgia Geral", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Dr. Thiago Vergílio – Urologista", area: "Urologia", cidade: "Porto Velho", uf: "RO", tipo: "Médico" },
  { nome: "Dr.Ultrassom – Seu exame na hora", area: "Diagnóstico Médico", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Dr. Valter Moura – Neurologia e Eletroencefalografia", area: "Neurologia", cidade: "Juazeiro do Norte", uf: "CE", tipo: "Médico" },
  { nome: "Dr. Vinicio Nunes – Ortopedista, Cirurgia da Coluna", area: "Ortopedia", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Dr. Walter Borges", area: "Ortopedia", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Durrari – Sociedade de Advogados", area: "Serviços Profissionais", cidade: "Varginha", uf: "MG", tipo: "Serviços" },
  { nome: "ECOMED – Clínica de Imagem", area: "Diagnóstico Médico", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Eduardo Jatene – Cirurgia Plástica", area: "Cirurgia Plástica", cidade: "Goiânia", uf: "GO", tipo: "Médico" },
  { nome: "Elielma Almeida Ferreira de", area: "Saúde da Mulher", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Evandro Luiz Brum – Cirurgia Torácica", area: "Cirurgia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Examine Agora – Imagem e Medicina", area: "Diagnóstico Médico", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Excellence – Clínica de Estética", area: "Dermatologia e Estética", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Fagundes Odontologia", area: "Odontologia", cidade: "São Paulo", uf: "SP", tipo: "Clínica" },
  { nome: "Fausto Stauffer – Cardiologista", area: "Cardiologia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Gastrus Clínica", area: "Gastroenterologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Grupo Santa Genoveva", area: "Saúde Geral", cidade: "Santa Helena de Goiás", uf: "GO", tipo: "Hospital" },
  { nome: "HighFive Clínica", area: "Saúde Geral", cidade: "Sorocaba", uf: "SP", tipo: "Clínica" },
  { nome: "HOLONS – Centro de Convivência Terapêutica", area: "Psicologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Hospital de Olhos do Distrito Federal", area: "Oftalmologia", cidade: "Brasília", uf: "DF", tipo: "Hospital" },
  { nome: "Hospital de Olhos Salute", area: "Oftalmologia", cidade: "Brasília", uf: "DF", tipo: "Hospital" },
  { nome: "Hospital do Olho de Araçatuba", area: "Oftalmologia", cidade: "Araçatuba", uf: "SP", tipo: "Hospital" },
  { nome: "Hospital Edmundo Fernandes", area: "Saúde Geral", cidade: "Uruaçu", uf: "GO", tipo: "Hospital" },
  { nome: "Hospital Virtual – Telemedicina", area: "Telemedicina", cidade: "Porto Velho", uf: "RO", tipo: "Clínica" },
  { nome: "ICB – Instituto de Câncer de Brasília", area: "Oncologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "ICMO – Instituto de Clínica e Microcirurgia Ocular", area: "Oftalmologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Ictus Cordis", area: "Cardiologia", cidade: "Marabá", uf: "PA", tipo: "Clínica" },
  { nome: "IMED", area: "Gastroenterologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "IMMI – Instituto de Medicina Minimamente Invasiva", area: "Medicina Vascular", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Imunocentro – Centro Integrado de Alergia, Pediatria e Vacinação", area: "Vacinação", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Inácio Ventura", area: "Ortopedia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Incordis", area: "Cardiologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "InMed – Instituto de Medicina e Diagnóstico", area: "Diagnóstico Médico", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Instituto CV", area: "Nutrição e Bem-Estar", cidade: "Salvador", uf: "BA", tipo: "Clínica" },
  { nome: "Instituto Kaplan", area: "Oncologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Instituto Panamericano de Oftalmologia", area: "Oftalmologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Instituto Sono e Neuro", area: "Medicina do Sono", cidade: "Balneário Camboriú", uf: "SC", tipo: "Clínica" },
  { nome: "ISAN – Instituto do Sono da Asa Norte", area: "Medicina do Sono", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "IV Congresso Brasileiro FENAESS", area: "Educação Médica", cidade: "Brasília", uf: "DF", tipo: "Evento" },
  { nome: "IVL – Instituto de Vascular e Laser", area: "Medicina Vascular", cidade: "Goiânia", uf: "GO", tipo: "Clínica" },
  { nome: "JK – Ortopedia e Clínica da Dor", area: "Ortopedia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "José Luiz Neto", area: "Cirurgia Plástica", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Labin-Med – Laboratório Clínico", area: "Laboratório", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Laser e Dermatologia Daher", area: "Dermatologia e Estética", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Laser Pelvi – Uroginecologia, Cirurgia Ginecológica e Laser", area: "Saúde da Mulher", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Layla Fayne", area: "Pneumologia", cidade: "Belo Horizonte", uf: "MG", tipo: "Médico" },
  { nome: "Life Centro Cardiológico", area: "Cardiologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Macrovisão Oftalmologia", area: "Oftalmologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Marcelle Castro", area: "Dermatologia e Estética", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Marcelo Bussi", area: "Saúde Geral", cidade: "Pindamonhangaba", uf: "SP", tipo: "Médico" },
  { nome: "Marcel Rebelato", area: "Dermatologia e Estética", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Matheus Campos", area: "Otorrinolaringologia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "MaxiCor Clínica", area: "Cardiologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "MaxImagem – Diagnóstico por Imagem", area: "Diagnóstico Médico", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "MB Home Care – Assistência Médica Domiciliar", area: "Saúde Geral", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Medco. Multiclínica", area: "Saúde Geral", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Melissa Chaves", area: "Dermatologia e Estética", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Mulier Laboratório Clínico", area: "Laboratório", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "NeoImagem – Clínica Radiológica", area: "Diagnóstico Médico", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "NOB – Núcleo de Otorrino de Brasília", area: "Otorrinolaringologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Oculare Oftalmologia", area: "Oftalmologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Oftalmoclínica do Planalto Central", area: "Oftalmologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Otonorte – Otorrinolaringologia", area: "Otorrinolaringologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Otoplus Saúde Plena – Otorrinolaringologia", area: "Otorrinolaringologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Otorrino Center", area: "Otorrinolaringologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "OxyCura – Clínica de Feridas Complexas", area: "Dermatologia e Estética", cidade: "Boa Vista", uf: "RR", tipo: "Clínica" },
  { nome: "Pelvi – Uroginecologia e Cirurgia Ginecológica", area: "Saúde da Mulher", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Plástica Plena", area: "Cirurgia Plástica", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Policlínica Corrente", area: "Saúde Geral", cidade: "Corrente", uf: "PI", tipo: "Clínica" },
  { nome: "ProPlástica", area: "Cirurgia Plástica", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Psicóloga Tatiana Mendes", area: "Psicologia", cidade: "São Caetano do Sul", uf: "SP", tipo: "Médico" },
  { nome: "Rodrigo Cruvinel – Cirurgião Plástico", area: "Cirurgia Plástica", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "Rodrigo Domingues – Ortopedista e Traumatologista, Cirurgia do Quadril", area: "Ortopedia", cidade: "Brasília", uf: "DF", tipo: "Médico" },
  { nome: "S2 Medica", area: "Saúde Geral", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Salus Ortopedia", area: "Ortopedia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Salute – Clínicas Especializadas", area: "Saúde Geral", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Saluti Clinica de Especialidades Médicas", area: "Saúde Geral", cidade: "Sorocaba", uf: "SP", tipo: "Clínica" },
  { nome: "SaúdeSim", area: "Saúde Geral", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "SBH – Sindicato Brasiliense de Hospitais", area: "Saúde Geral", cidade: "Brasília", uf: "DF", tipo: "Associação" },
  { nome: "Scitec – Soluções de Ensaios de Materiais e Produtos", area: "Laboratório", cidade: "Palhoça", uf: "SC", tipo: "Laboratório" },
  { nome: "Sense Ginecologia Ltda", area: "Saúde da Mulher", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Sinapse Neurologia", area: "Neurologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Sociedade Brasiliense de Doenças Torácicas", area: "Medicina Respiratória", cidade: "Brasília", uf: "DF", tipo: "Associação" },
  { nome: "Sorriso.com", area: "Odontologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Studio Schwerz", area: "Saúde Geral", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "TireoideWeb", area: "Endocrinologia", cidade: "Brasília", uf: "DF", tipo: "Website" },
  { nome: "TrabImagem – Radiodiagnóstico Acessível", area: "Diagnóstico Médico", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Única – Assistência Domiciliar em Saúde Mental", area: "Psiquiatria", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Unna Vitta", area: "Saúde Geral", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Urocentro", area: "Urologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Urodiagnóstico – Centro de Urologia", area: "Urologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "UROS – Urologia, Robótica, Oncologia e Sexualidade", area: "Urologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "USB – Unidade do Sono de Brasília", area: "Medicina do Sono", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Vanessa Puppio", area: "Saúde Geral", cidade: "Pindamonhangaba", uf: "SP", tipo: "Clínica" },
  { nome: "Vascular Brasília – Cirurgia Vascular e Endovascular", area: "Medicina Vascular", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Via Oftalmocenter", area: "Oftalmologia", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Virtus – Clínica, App", area: "Saúde Geral", cidade: "Brasília", uf: "DF", tipo: "Clínica" },
  { nome: "Visual Med Imperatriz", area: "Saúde da Mulher", cidade: "Imperatriz", uf: "MA", tipo: "Clínica" },
  { nome: "Viviane Puppio", area: "Saúde Geral", cidade: "Pindamonhangaba", uf: "SP", tipo: "Clínica" },
  { nome: "Wanessa Sigiane – Cirurgia Plástica", area: "Cirurgia Plástica", cidade: "Brasília", uf: "DF", tipo: "Médico" },
];
