// Portfólio do acervo — SÓ composição/mockup pronta; post cru de rede social NÃO
// entra (regra do cliente, 2026-08-11: "post antigo cru não pode entrar; o certo é
// composição/mockup; contexto bem pouco, mais pra marcar palavra-chave").
//
// Fonte da verdade da frente: rizzo-os → docs/ACERVO_PLANO_PAGINAS_MAPA.md §16.
// Regras de entrada (mecânicas — checar-portfolio.mjs derruba o build se quebrar):
//   1. Cliente é NOME PÚBLICO, grafia exata das listas do repo (§15.4/§20).
//   2. A atribuição saiu de LER A IMAGEM (marca/logo na arte) — §34.
//   3. `contexto` é UMA linha curta, escrita pra palavra-chave (serviço ·
//      especialidade · praça) — NUNCA taxonomia interna de sprint.
//   4. Arquivo em public/portfolio/ com NOME-SLUG DE PALAVRA-CHAVE (a convenção do
//      site antigo: _3 criativos/marketing-cirurgiao-vascular-…), webp ≤1200px.
//      É dele que sai a âncora da peça (#peca-<nome-do-arquivo>) — arquivo repetido
//      em duas pastas = âncora repetida, e o checador reprova.
//   5. `espec` de LISTA FECHADA (as `area` de clientes.ts normalizadas + a lista
//      ESPECIALIDADES_EXTRA), `servico` e `praca` (Cidade/UF) preenchidos: são o
//      agrupamento e a meta da parede — padrão de apresentação no handoff
//      design_handoff_parede_portfolio/ (rizzo-os), §16.5 do doc-mapa.
// Onde achar mais: gênero "Portfólio virtual - <Cliente>" + subpastas mockup/ dos
// sprints peca_grafica_portfolio (79 docs no índice). O one-pager LONGO não entra
// na grade — só a composição (celular/moldura); quando o cliente só tiver o longo,
// compor mockup novo com skill de design a partir dele.
// Lote = ADICIONAR linhas; tirar do ar = remover linha (ajuste no ar = revert).

export interface PecaPortfolio {
  /** Nome público, grafia EXATA da lista onde ele já aparece. */
  cliente: string;
  /** 1 linha curta de contexto, escrita pra palavra-chave — vira a legenda. */
  contexto: string;
  /**
   * Especialidade — o eixo do agrupamento da parede. LISTA FECHADA (ver
   * ESPECIALIDADES_EXTRA abaixo); `checar-portfolio.mjs` derruba o build no valor
   * de fora. NUNCA derivar do `contexto` por heurística (§24.9/§34: a arte é a
   * fonte, nome não se casa por adivinhação).
   */
  espec: string;
  /** Serviço entregue, como a agência nomeia. Com a praça, forma a meta da linha. */
  servico: string;
  /** Praça no formato `Cidade/UF`, igual ao cadastro público da carteira. */
  praca: string;
  /** Caminho em /public — nome do arquivo é slug de palavra-chave. */
  imagem: string;
  largura: number;
  altura: number;
  alt: string;
  /** Slugs de carta onde a peça aparece como prova (além do /clientes). */
  cartas: string[];
  /** Rastreabilidade no Dropbox (não renderiza). */
  origem: string;
}

/**
 * A lista fechada de `espec` é DERIVADA no build das `area` de content/clientes.ts,
 * normalizadas (o campo mistura especialidade e praça: "Oftalmologia · DF"). Quem
 * cobra é scripts/checar-portfolio.mjs — não existe cópia da lista aqui pra
 * dessincronizar.
 *
 * Aqui ficam SÓ as especialidades que a lista de clientes não tem termo pra dizer.
 * Linha nova aqui é decisão visível no diff; não é lugar de sinônimo do que a lista
 * já diz — cada uma abaixo entrou porque a ARTE de uma peça a nomeia e a lista
 * derivada de clientes.ts não tem como dizê-la.
 *
 * ⚠️ Aspas duplas NÃO entram nos comentários deste array: o checar-portfolio.mjs lê a
 * lista com /"([^"]+)"/g dentro dos colchetes, então qualquer trecho citado aqui
 * viraria espec válida em silêncio — o gate afrouxa sem ninguém ver.
 */
export const ESPECIALIDADES_EXTRA = [
  // A S2 Medica está na carteira como Saúde Geral, balde genérico do gerador, não
  // especialidade. Também cobre centro médico/policlínica sem recorte único.
  "Clínica Médica",
  // Lote 2 (2026-08-11) — cada uma lida na ARTE da peça que a estreia:
  "Nefrologia", // Clínica do Rim e Hipertensão: folder lista nefrologia, diálise, hemodiálise
  "Gastroenterologia", // IMED: Instituto Médico Cirúrgico do Aparelho Digestivo, endoscopia
  "Cirurgia do Aparelho Digestivo", // Dr. Thiago Becker: cirurgia digestiva • bariátrica no logo
  "Oncologia", // CON (oncologia e hematologia) e Dra. Rayane Cardoso (cirurgia oncológica)
  "Nutrologia", // Dr. Celso Melo: Nutrólogo em Brasília no hero do site
  // Lote 2, rodada 2 (2026-08-11) — cada uma lida na ARTE da peça que a estreia:
  "Neurocirurgia", // Dr. Auricelio Batista Cezar Júnior: NEUROCIRURGIA no logo do site
  "Cirurgia Plástica", // Dra. Mariana Alcantara: pasta institucional de cirurgia plástica
  "Medicina da Dor", // Medicina da Dor, clínica da Dra. Ana Cristina Medanha em Araguaína
];

/**
 * Chave de comparação/âncora: sem acento, sem pontuação, minúscula. Mora aqui (e não
 * no page.tsx, de onde veio) porque agora tem DOIS consumidores: o `area-<chave>` da
 * carteira e o `parede-<chave>` desta parede. Uma função só = os dois nunca divergem.
 */
export const chave = (s: string) =>
  s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "");

export const PORTFOLIO: PecaPortfolio[] = [
  {
    cliente: "Dr. Eder Nisi Ilario – Urologista/Uro-oncologista",
    contexto: "Marketing médico para urologia e cirurgia robótica — São Paulo",
    espec: "Urologia",
    servico: "Portfólio digital",
    praca: "São Paulo/SP",
    imagem: "/portfolio/marketing-medico-urologia-sao-paulo-portfolio.webp",
    largura: 1200,
    altura: 1200,
    alt: "Mockup de celular com o portfólio digital do Dr. Eder Nisi Ilario, urologista e uro-oncologista em São Paulo",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2022/EN/sprint_5_EN_peca_grafica_portfolio/v2/apres/Mockup.png",
  },
  {
    cliente: "Urocentro",
    contexto: "Identidade digital para clínica de urologia — Brasília",
    espec: "Urologia",
    servico: "Identidade",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-urologia-brasilia-mockup.webp",
    largura: 1200,
    altura: 900,
    alt: "Mockup de celular com o portfólio digital do Urocentro, clínica de urologia em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Urocentro/2023/UC/sprint_2_UC_peca_grafica_portfolio/v1/apres/compressed",
  },
  {
    cliente: "S2 Medica",
    contexto: "Redes sociais para clínica médica — Brasília",
    espec: "Clínica Médica",
    servico: "Redes sociais",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-redes-sociais-brasilia-mockup.webp",
    largura: 1200,
    altura: 900,
    alt: "Composição com posts de Instagram criados para a S2 Médica: datas de saúde e conteúdo educativo",
    cartas: ["redes-sociais", "clinicas-e-consultorios"],
    origem: "/Clientes/_insumos/_site_agencia_rizzo/_2 mockups/mockup_redes_sociais_1.jpg",
  },
  {
    cliente: "Casa de Saúde de Remanso",
    contexto: "Folder institucional para hospital — Remanso, Bahia",
    espec: "Hospital",
    servico: "Folder institucional",
    praca: "Remanso/BA",
    imagem: "/portfolio/marketing-hospital-remanso-bahia-folder-institucional.webp",
    largura: 1200,
    altura: 700,
    alt: "Folder institucional impresso da Casa de Saúde de Remanso, hospital em Remanso, na Bahia",
    cartas: ["rede-hospitalar"],
    origem: "/Clientes/2022/SR/sprint_9_SR_peca_grafica_portfolio/v1/apres/Mockup2.png",
  },
  {
    cliente: "Casa de Saúde de Remanso",
    contexto: "Cartão de visita para hospital — Remanso, Bahia",
    espec: "Hospital",
    servico: "Cartão de visita",
    praca: "Remanso/BA",
    imagem: "/portfolio/marketing-hospital-remanso-bahia-cartao-visita.webp",
    largura: 1200,
    altura: 892,
    alt: "Cartão de visita frente e verso da Casa de Saúde de Remanso, hospital em Remanso, na Bahia",
    cartas: ["rede-hospitalar"],
    origem: "/Clientes/2023/SR/sprint_17_SR_peca_grafica_cartao_visita_u0/mockup/mockup.jpg",
  },
  {
    cliente: "Clínica do Rim e Hipertensão",
    contexto: "Portfólio digital para clínica de nefrologia — Valparaíso de Goiás",
    espec: "Nefrologia",
    servico: "Portfólio digital",
    praca: "Valparaíso de Goiás/GO",
    imagem: "/portfolio/marketing-medico-nefrologia-valparaiso-goias-portfolio-digital.webp",
    largura: 1200,
    altura: 801,
    alt: "Mockup de celular com o portfólio digital da Clínica do Rim e Hipertensão, nefrologia em Valparaíso de Goiás",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2023/CR/sprint_13_CR_peca_grafica_portfolio/mockup/mockup_celular_mao.jpg",
  },
  {
    cliente: "Clínica do Rim e Hipertensão",
    contexto: "Folder de serviços para clínica de nefrologia e diálise — Valparaíso de Goiás",
    espec: "Nefrologia",
    servico: "Folder institucional",
    praca: "Valparaíso de Goiás/GO",
    imagem: "/portfolio/marketing-medico-nefrologia-valparaiso-goias-folder-servicos.webp",
    largura: 1200,
    altura: 840,
    alt: "Folder impresso da Clínica do Rim e Hipertensão com os serviços de nefrologia, diálise e hemodiálise",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2023/CR/sprint_13_CR_peca_grafica_portfolio/v1/apres/Mockup_folder.jpg",
  },
  {
    cliente: "IMED",
    contexto: "Portfólio digital para clínica de gastroenterologia — Brasília",
    espec: "Gastroenterologia",
    servico: "Portfólio digital",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-gastroenterologia-brasilia-portfolio-digital.webp",
    largura: 1200,
    altura: 800,
    alt: "Mockup de celular com o portfólio digital do IMED, clínica de gastroenterologia e endoscopia em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Imed - Endoscopia e Colonoscopia/2023/ED/sprint_17_ED_peca_grafica_portfolio/mockup/Mockup_Celular.png",
  },
  {
    cliente: "IMED",
    contexto: "Folder impresso para clínica de endoscopia e coloproctologia — Brasília",
    espec: "Gastroenterologia",
    servico: "Folder institucional",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-gastroenterologia-brasilia-folder-impresso.webp",
    largura: 1200,
    altura: 795,
    alt: "Folder impresso de três dobras do IMED, com especialidades, exames e corpo clínico",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Imed - Endoscopia e Colonoscopia/2023/ED/sprint_17_ED_peca_grafica_portfolio/v1/apres/Mockup_folder.png",
  },
  {
    cliente: "Dra. Daniele Pollo – Oftalmologista",
    contexto: "Portfólio impresso para oftalmologista — Parauapebas",
    espec: "Oftalmologia",
    servico: "Portfólio impresso",
    praca: "Parauapebas/PA",
    imagem: "/portfolio/marketing-medico-oftalmologia-parauapebas-portfolio-impresso.webp",
    largura: 1200,
    altura: 783,
    alt: "Portfólio impresso da Dra. Daniele Pollo, oftalmologista em Parauapebas",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Daniele Carretero Pollo/2023/DE/sprint_14_DE_peca_grafica_portfolio/v1/apres/Mockup_impresso.png",
  },
  {
    cliente: "Centro Médico Navegantes",
    contexto: "Portfólio digital para centro médico — Rio de Janeiro",
    espec: "Clínica Médica",
    servico: "Portfólio digital",
    praca: "Rio de Janeiro/RJ",
    imagem: "/portfolio/marketing-clinica-medica-rio-de-janeiro-portfolio-digital.webp",
    largura: 1200,
    altura: 801,
    alt: "Mockup de celular com o portfólio digital do Centro Médico Navegantes, no Rio de Janeiro",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Centro Médico Navegantes do Brasil/2023/NV/sprint_8_NV_peca_grafica_portfolio/mockup/mockup_hand_mobile.jpg",
  },
  {
    cliente: "Centro Médico Navegantes",
    contexto: "Folder institucional para centro médico e odontológico — Rio de Janeiro",
    espec: "Clínica Médica",
    servico: "Folder institucional",
    praca: "Rio de Janeiro/RJ",
    imagem: "/portfolio/marketing-clinica-medica-rio-de-janeiro-folder-institucional.webp",
    largura: 1200,
    altura: 800,
    alt: "Folder impresso do Centro Médico Navegantes, com serviços prestados e corpo clínico",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Centro Médico Navegantes do Brasil/2023/NV/sprint_8_NV_peca_grafica_portfolio/mockup/mockup foler.png",
  },
  {
    cliente: "CLIAOD – Otorrinolaringologia",
    contexto: "Folder institucional para clínica de otorrinolaringologia — Brasília",
    espec: "Otorrinolaringologia",
    servico: "Folder institucional",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-otorrinolaringologia-brasilia-folder-institucional.webp",
    largura: 1200,
    altura: 795,
    alt: "Folder impresso da CLIAOD, clínica de otorrinolaringologia e audiologia em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Cliaod/Design/2023/LI/sprint_2_LI_peca_grafica_portfolio_refacao/mockup/mockup_folder.jpg",
  },
  {
    cliente: "CLIAOD – Otorrinolaringologia",
    contexto: "Portfólio digital para clínica de otorrino e audiologia — Brasília",
    espec: "Otorrinolaringologia",
    servico: "Portfólio digital",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-otorrinolaringologia-brasilia-portfolio-digital.webp",
    largura: 1200,
    altura: 900,
    alt: "Mockup de celular com o portfólio digital da CLIAOD, otorrinolaringologia em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Cliaod/Design/2022/LI/sprint_16_LI_peca_grafica_portfolio_refacao/v1/mockup/Sansung Galaxy S9 Mockup LI_2.jpg",
  },
  {
    cliente: "Dr. Thiago Becker – Cirurgia Gástrica e Bariátrica",
    contexto: "Portfólio digital para cirurgião do aparelho digestivo — Goiânia",
    espec: "Cirurgia do Aparelho Digestivo",
    servico: "Portfólio digital",
    praca: "Goiânia/GO",
    imagem: "/portfolio/marketing-medico-cirurgia-digestiva-goiania-portfolio-digital.webp",
    largura: 1200,
    altura: 1200,
    alt: "Mockup de celular com o portfólio digital do Dr. Thiago Becker, cirurgião do aparelho digestivo",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Thiago Becker/2023/CK/sprint_13_CK_portifolio/mockup/Mockup_phone.png",
  },
  {
    cliente: "Dr. Thiago Becker – Cirurgia Gástrica e Bariátrica",
    contexto: "Folder impresso para cirurgia digestiva e bariátrica — Goiânia",
    espec: "Cirurgia do Aparelho Digestivo",
    servico: "Folder institucional",
    praca: "Goiânia/GO",
    imagem: "/portfolio/marketing-medico-cirurgia-digestiva-goiania-folder-impresso.webp",
    largura: 1200,
    altura: 795,
    alt: "Folder impresso do Dr. Thiago Becker, com especialidades e tratamentos em cirurgia digestiva e bariátrica",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Thiago Becker/2023/CK/sprint_13_CK_portifolio/v1/apres/folder_mockup.png",
  },
  {
    cliente: "Dr. Thiago Becker – Cirurgia Gástrica e Bariátrica",
    contexto: "E-book sobre pós-operatório da cirurgia bariátrica — Goiânia",
    espec: "Cirurgia do Aparelho Digestivo",
    servico: "E-book",
    praca: "Goiânia/GO",
    imagem: "/portfolio/marketing-medico-cirurgia-bariatrica-goiania-ebook.webp",
    largura: 1200,
    altura: 900,
    alt: "Mockup de celular com a capa do e-book do Dr. Thiago Becker sobre suplementação no pós-operatório da cirurgia bariátrica",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Thiago Becker/2024/CK/sprint_17_CK_peca_grafica_ebook_u0/apres/iPhone_Mockup_1.png",
  },
  {
    cliente: "Dr. Fernando Ferro",
    contexto: "Pasta institucional para ortopedista — Goiânia",
    espec: "Ortopedia e Traumatologia",
    servico: "Pasta institucional",
    praca: "Goiânia/GO",
    imagem: "/portfolio/marketing-medico-ortopedia-goiania-pasta-institucional.webp",
    largura: 1200,
    altura: 900,
    alt: "Pasta institucional impressa do Dr. Fernando Ferro, ortopedia e traumatologia em Goiânia",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2024/FF/sprint_14_FF_peca_grafica_portfolio/insumos/sprint_14_FF_peca_grafica_portfolio_mockup.png",
  },
  {
    cliente: "Dr. Fernando Ferro",
    contexto: "Site para cirurgia do quadril — Goiânia",
    espec: "Ortopedia e Traumatologia",
    servico: "Site",
    praca: "Goiânia/GO",
    imagem: "/portfolio/marketing-medico-ortopedia-goiania-site-cirurgia-quadril.webp",
    largura: 1200,
    altura: 500,
    alt: "Mockup de monitor com o site do Dr. Fernando Ferro, cirurgia do quadril em Goiânia",
    cartas: ["site-seo", "clinicas-e-consultorios"],
    origem: "/Clientes/2024/FF/sprint_9_FF_site_prototipo_finalizacao_u0/v1/apres/site_mockup_FF.jpg",
  },
  {
    cliente: "Policlínica Corrente",
    contexto: "Outdoor para policlínica — Corrente, Piauí",
    espec: "Clínica Médica",
    servico: "Outdoor",
    praca: "Corrente/PI",
    imagem: "/portfolio/marketing-clinica-medica-corrente-piaui-outdoor.webp",
    largura: 1200,
    altura: 899,
    alt: "Outdoor da Policlínica de Corrente anunciando atendimento em especialidades e exames de imagem",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2025/PO/sprint_8_PO_peca_grafica_outdoor/apres/Billboard Mockup.png",
  },
  {
    cliente: "Incordis",
    contexto: "Folder institucional para clínica de cardiologia e cirurgia vascular — Brasília",
    espec: "Cardiologia",
    servico: "Folder institucional",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-cardiologia-brasilia-folder-institucional.webp",
    largura: 1200,
    altura: 964,
    alt: "Folder institucional da Incordis, cardiologia e cirurgia vascular em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2025/IN/sprint_4_IN_peca_grafica_folder/apres/Folder_completo_mockup.png",
  },
  {
    cliente: "Otoplus Saúde Plena – Otorrinolaringologia",
    contexto: "Sinalização de ambiente para clínica de otorrinolaringologia — Brasília",
    espec: "Otorrinolaringologia",
    servico: "Sinalização",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-otorrinolaringologia-brasilia-sinalizacao-clinica.webp",
    largura: 955,
    altura: 1200,
    alt: "Placas de sinalização de silêncio da Otoplus instaladas em ambiente de clínica",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/OtoPlus/2023/OP/sprint_12_OP_peca_grafica_placa_silencio_u0/v3/apres/mockup_1.png",
  },
  {
    cliente: "Clínica Renovare – Urologia e Andrologia",
    contexto: "Cartão de visita para clínica de urologia e andrologia — Brasília",
    espec: "Urologia",
    servico: "Cartão de visita",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-urologia-brasilia-cartao-visita.webp",
    largura: 1200,
    altura: 800,
    alt: "Cartão de visita frente e verso da Clínica Renovare, urologia e andrologia em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Clínica Renovare/2023/sprint_8_RN_papelaria_nova_unidade_u0/mockup/mockup cartao de visita.png",
  },
  {
    cliente: "CON – Clínica Oncologia Hematologia",
    contexto: "Panfleto de nova unidade para clínica de oncologia — Rio de Janeiro",
    espec: "Oncologia",
    servico: "Panfleto",
    praca: "Rio de Janeiro/RJ",
    imagem: "/portfolio/marketing-medico-oncologia-rio-de-janeiro-panfleto-unidade.webp",
    largura: 1200,
    altura: 1200,
    alt: "Panfleto impresso da CON anunciando a nova unidade de oncologia, hematologia e centro de infusão",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/CON – Oncologia, Hematologia e Centro de Infusão/2024/sprint_5_CO_peca_grafica_panfleto_sao_goncalo/mockup/mockup.png",
  },
  {
    cliente: "Dr. Douglas Pigosso",
    contexto: "E-book sobre descolamento de retina para oftalmologista — Brasília",
    espec: "Oftalmologia",
    servico: "E-book",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-oftalmologia-brasilia-ebook-retina.webp",
    largura: 1200,
    altura: 800,
    alt: "Tablet e celular com o e-book do Dr. Douglas Pigosso sobre descolamento de retina",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Douglas Pigosso/2025/DP/sprint_3_DP_peca_grafica_ebook/apres/Free iPhone & iPad Mockup.jpg",
  },
  {
    cliente: "Dr. Tiago Amaral",
    contexto: "Site para ortopedista de quadril e joelho — Goiânia",
    espec: "Ortopedia e Traumatologia",
    servico: "Site",
    praca: "Goiânia/GO",
    imagem: "/portfolio/marketing-medico-ortopedia-goiania-site-quadril-joelho.webp",
    largura: 1200,
    altura: 500,
    alt: "Mockup de monitor com o site do Dr. Tiago Amaral, ortopedista de quadril e joelho em Goiânia",
    cartas: ["site-seo", "clinicas-e-consultorios"],
    origem: "/Clientes/2024/TA/sprint_15_TA_site_landing/apres/site_mockup_TA.jpg",
  },
  {
    cliente: "Dra. Rayane Cardoso",
    contexto: "Site para cirurgia oncológica e laparoscópica — Brasília",
    espec: "Oncologia",
    servico: "Site",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-oncologia-brasilia-site-cirurgia-oncologica.webp",
    largura: 1200,
    altura: 500,
    alt: "Mockup de monitor com o site da Dra. Rayane Cardoso, cirurgia oncológica e laparoscópica em Brasília",
    cartas: ["site-seo", "clinicas-e-consultorios"],
    origem: "/Clientes/2024/RY/sprint_8_RY_landing_page_migracao_site_completo_u0/v1/apres/site_mockup_RY.jpg",
  },
  {
    cliente: "Dra. Rayane Cardoso",
    contexto: "E-book sobre câncer de colo do útero — Brasília",
    espec: "Oncologia",
    servico: "E-book",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-oncologia-brasilia-ebook-cancer-colo-utero.webp",
    largura: 1200,
    altura: 800,
    alt: "Tablet com o e-book da Dra. Rayane Cardoso sobre a jornada do paciente com câncer de colo do útero",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2025/RY/sprint_4_RY_ebook_jornada_paciente/insumos/mockup/MockupMaison_Tablet_TB-E-03_preveiw2.png",
  },
  {
    cliente: "Dr. Rodrigo Villalva",
    contexto: "Site para urologia e cirurgia robótica — Brasília",
    espec: "Urologia",
    servico: "Site",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-urologia-brasilia-site-cirurgia-robotica.webp",
    largura: 1200,
    altura: 500,
    alt: "Mockup de monitor com o site do Dr. Rodrigo Villalva, urologia e cirurgia robótica em Brasília",
    cartas: ["site-seo", "clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Rodrigo Villalva/2024/RV/sprint_8_RV_landing_page_migracao_site_completo_u0/v1/apres/mockup/site_mockup_RV.jpg",
  },
  {
    cliente: "Dra. Fabyanne Mazutti",
    contexto: "Site para ginecologia e reprodução humana — Brasília",
    espec: "Saúde da Mulher",
    servico: "Site",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-ginecologia-brasilia-site.webp",
    largura: 1200,
    altura: 500,
    alt: "Mockup de monitor com o site da Dra. Fabyanne Mazutti, ginecologista em Brasília",
    cartas: ["site-seo", "clinicas-e-consultorios"],
    origem: "/Clientes/2024/FZ/sprint_17_FZ_site_prototipo_u0/apres/mockup/site_mockup_FZ.jpg",
  },
  {
    cliente: "Dr. Celso Melo – Nutrólogo",
    contexto: "Site para nutrologia — Brasília",
    espec: "Nutrologia",
    servico: "Site",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-nutrologia-brasilia-site.webp",
    largura: 1200,
    altura: 500,
    alt: "Mockup de monitor com o site do Dr. Celso Melo, nutrólogo em Brasília",
    cartas: ["site-seo", "clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Celso de Paiva Melo/2024/CE/sprint_9_CE_landing_page_u0/v1/apres/site_mockup_CE_Landing.jpg",
  },
  {
    cliente: "Clínica VivaVita",
    contexto: "Site para clínica de medicina integrativa — Pindamonhangaba",
    espec: "Clínica Médica",
    servico: "Site",
    praca: "Pindamonhangaba/SP",
    imagem: "/portfolio/marketing-clinica-medica-pindamonhangaba-site.webp",
    largura: 1200,
    altura: 500,
    alt: "Mockup de monitor com o site da Clínica VivaVitá, medicina integrativa em Pindamonhangaba",
    cartas: ["site-seo", "clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Clínica VivaVitá/2024/VT/sprint_1_VT_site_prototipo/v2/apres/site_mockup_VT_v3.jpg",
  },
  {
    cliente: "Instituto CV",
    contexto: "Landing page de tratamento para menopausa — Salvador",
    espec: "Saúde da Mulher",
    servico: "Site",
    praca: "Salvador/BA",
    imagem: "/portfolio/marketing-medico-menopausa-salvador-site.webp",
    largura: 1200,
    altura: 500,
    alt: "Mockup de monitor com a landing page do Instituto CV sobre tratamento para menopausa em Salvador",
    cartas: ["site-seo", "clinicas-e-consultorios"],
    origem: "/Clientes/2024/CI/sprint_8_CI_landing_page_menopausa_salvador_u0/v1/apres/site_landing_mockup_CI_2.jpg",
  },
  {
    cliente: "Dr. Homero Ribeiro",
    contexto: "E-book sobre vasectomia para urologista — Brasília",
    espec: "Urologia",
    servico: "E-book",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-urologia-brasilia-ebook-vasectomia.webp",
    largura: 1200,
    altura: 768,
    alt: "E-book impresso do Dr. Homero Ribeiro sobre vasectomia, urologia e sexologia",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2024/HR/sprint_8_HR_peca_grafica_ebook_atualizacao_refacao/v1/mockup/Horizontal_Book_Mockup_6.png",
  },
  {
    cliente: "Dra. Maria Eduarda Amaral",
    contexto: "E-book sobre fertilidade para ginecologia e reprodução humana — Brasília",
    espec: "Saúde da Mulher",
    servico: "E-book",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-reproducao-humana-brasilia-ebook-fertilidade.webp",
    largura: 1200,
    altura: 833,
    alt: "Mockup de celular com o e-book da Dra. Maria Eduarda Amaral sobre medidas para otimizar a fertilidade natural",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2025/ME/sprint_4_ME_peca_grafica_ebook/apres/mockup.png",
  },
  {
    cliente: "Dr. Antonio Carlos de Souza",
    contexto: "Folder educativo sobre lipedema para cirurgia vascular — Brasília",
    espec: "Angiologia e Vascular",
    servico: "Folder educativo",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-vascular-brasilia-folder-lipedema.webp",
    largura: 1200,
    altura: 800,
    alt: "Folder educativo do Dr. Antonio Carlos de Souza sobre lipedema, angiologia e cirurgia vascular",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2025/AN/sprint_3_AN_folder_lipedema/mockup/mockup.png",
  },
  {
    cliente: "Cardio Clinic",
    contexto: "Papelaria para clínica de cardiologia — Parauapebas",
    espec: "Cardiologia",
    servico: "Papelaria",
    praca: "Parauapebas/PA",
    imagem: "/portfolio/marketing-medico-cardiologia-parauapebas-papelaria.webp",
    largura: 1200,
    altura: 900,
    alt: "Papel timbrado da Cardio Clinic, clínica de cardiologia em Parauapebas",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2025/CD/sprint_6_CD_peca_grafica_timbrado/apres/A4_Flyer_Mockup_2.jpg",
  },
  {
    cliente: "Instituto Sono e Neuro",
    contexto: "Padronização de redes sociais para instituto de medicina do sono — Balneário Camboriú",
    espec: "Medicina do Sono",
    servico: "Redes sociais",
    praca: "Balneário Camboriú/SC",
    imagem: "/portfolio/marketing-medico-medicina-do-sono-balneario-camboriu-redes-sociais.webp",
    largura: 1200,
    altura: 675,
    alt: "Mockup de notebook com a capa de Facebook padronizada do Instituto Sono e Neuro",
    cartas: ["redes-sociais", "clinicas-e-consultorios"],
    origem: "/Clientes/2025/SN/sprint_3_SN_padronizacao_redes_sociais/apres/mockup_capa_facebook.png",
  },
  // Lote 2, rodada 2 (2026-08-11) — busca do conector Dropbox (mockup/apres), não do
  // indice-sprints.csv (emenda §16.6-2 do doc-mapa).
  {
    cliente: "Dr. Felipe Mendonça",
    contexto: "Portfólio impresso para cirurgia vascular e endovascular — Goiânia",
    espec: "Angiologia e Vascular",
    servico: "Portfólio impresso",
    praca: "Goiânia/GO",
    imagem: "/portfolio/marketing-medico-cirurgia-vascular-goiania-portfolio-impresso.webp",
    largura: 1200,
    altura: 780,
    alt: "Folder impresso do Dr. Felipe Mendonça, cirurgião vascular e endovascular em Goiânia",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2021/FM/sprint_8_FM_portfolio_servicos/apres/mockup/Mockup_01.png",
  },
  {
    cliente: "MaxiCor Clínica",
    contexto: "Portfólio impresso para clínica de cardiologia — Brasília",
    espec: "Cardiologia",
    servico: "Portfólio impresso",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-cardiologia-brasilia-portfolio-impresso.webp",
    largura: 1200,
    altura: 793,
    alt: "Portfólio impresso da MaxiCor Clínica, cardiologia em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Maxicor Clínica/2021/AX/sprint_8_AX_portfolio_impresso_servicos/apres/Mockup/Mockup 1.png",
  },
  {
    cliente: "Dr. Auricelio Batista Cezar Júnior",
    contexto: "Site para neurocirurgia e tratamento de metástases cerebrais — Recife",
    espec: "Neurocirurgia",
    servico: "Site",
    praca: "Recife/PE",
    imagem: "/portfolio/marketing-medico-neurocirurgia-recife-site.webp",
    largura: 1200,
    altura: 500,
    alt: "Mockup de monitor com o site do Dr. Auricelio Batista Cezar Júnior, neurocirurgia em Recife",
    cartas: ["site-seo", "clinicas-e-consultorios"],
    origem: "/Clientes/2024/AU/sprint_3_AU_site_landing/insumos/mockup1.jpg",
  },
  {
    cliente: "Via Oftalmocenter",
    contexto: "Banner de prevenção ao glaucoma para clínica de oftalmologia — Brasília",
    espec: "Oftalmologia",
    servico: "Banner",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-oftalmologia-brasilia-banner-glaucoma.webp",
    largura: 1099,
    altura: 1200,
    alt: "Banner da Via Oftalmocenter sobre prevenção de glaucoma, oftalmologia em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2025/VO/sprint_3_VO_peca_grafica_banner/insumos/mockup_banner.png",
  },
  {
    cliente: "Via Oftalmocenter",
    contexto: "Folder sobre trabeculoplastia a laser para tratamento de glaucoma — Brasília",
    espec: "Oftalmologia",
    servico: "Folder educativo",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-oftalmologia-brasilia-folder-trabeculoplastia.webp",
    largura: 1200,
    altura: 840,
    alt: "Folder impresso da Via Oftalmocenter sobre trabeculoplastia seletiva a laser",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2021/VO/sprint_5_VO_folder_u0/mockup/Bifold_A4_Mockup.jpg",
  },
  {
    cliente: "Dr. Allan Garcia",
    contexto: "Conjunto de banners para cirurgia da coluna — Grande Vitória e Linhares",
    espec: "Ortopedia e Traumatologia",
    servico: "Banner",
    praca: "Vitória/ES",
    imagem: "/portfolio/marketing-medico-ortopedia-vitoria-banner-coluna.webp",
    largura: 1200,
    altura: 778,
    alt: "Conjunto de banners do Dr. Allan Garcia sobre cirurgia da coluna, hérnia de disco e escoliose",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2025/AL/sprint_3_AL_peca_grafica_banner_google/apres/mockup.jpg",
  },
  {
    cliente: "Dra. Rhaiana Gondim – Urologia e Uropediatria",
    contexto: "Cartão de visita para urologista e uropediatra — Brasília",
    espec: "Urologia",
    servico: "Cartão de visita",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-urologia-brasilia-cartao-visita-uropediatria.webp",
    largura: 1200,
    altura: 900,
    alt: "Cartão de visita da Dra. Rhaiana Gondim, urologia e uropediatria em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Rhaiana Gondim/2021/RH/sprint_14_RH_peca_grafica_portfolio_u0/v1/apres/Mockup/Mockup-1.png",
  },
  {
    cliente: "Dr. Thiago Vergílio – Urologista",
    contexto: "Portfólio impresso para urologista especialista em uro-oncologia — Porto Velho",
    espec: "Urologia",
    servico: "Portfólio impresso",
    praca: "Porto Velho/RO",
    imagem: "/portfolio/marketing-medico-urologia-porto-velho-portfolio-impresso.webp",
    largura: 1200,
    altura: 900,
    alt: "Portfólio impresso do Dr. Thiago Vergílio, urologista especialista em uro-oncologia em Porto Velho",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Thiago Perondi Vergilio/2021/TH/sprint_5_TH_portfolio_servicos/apres/impresso/Mockup_01.jpg",
  },
  {
    cliente: "Dr. Renan R. Marangoni – Cirurgia do Aparelho Digestivo, Cirurgia Geral",
    contexto: "Site para cirurgia de diástase abdominal — Goiânia",
    espec: "Cirurgia do Aparelho Digestivo",
    servico: "Site",
    praca: "Goiânia/GO",
    imagem: "/portfolio/marketing-medico-cirurgia-digestiva-goiania-site-diastase.webp",
    largura: 1200,
    altura: 500,
    alt: "Mockup de monitor com o site do Dr. Renan R. Marangoni sobre cirurgia de diástase abdominal em Goiânia",
    cartas: ["site-seo", "clinicas-e-consultorios"],
    origem: "/Clientes/2024/RM/sprint_8_RM_site_landing/insumos/site_landing_mockup.jpg",
  },
  {
    cliente: "Dr. Renan R. Marangoni – Cirurgia do Aparelho Digestivo, Cirurgia Geral",
    contexto: "E-book sobre gastrite para cirurgia do aparelho digestivo — Goiânia",
    espec: "Cirurgia do Aparelho Digestivo",
    servico: "E-book",
    praca: "Goiânia/GO",
    imagem: "/portfolio/marketing-medico-cirurgia-digestiva-goiania-ebook-gastrite.webp",
    largura: 1200,
    altura: 800,
    alt: "Mockup de celular com o e-book do Dr. Renan R. Marangoni sobre gastrite",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2022/RM/sprint_4_RM_peca_grafica_ebook/v1/insumos/mockup1.png",
  },
  {
    cliente: "Dra. Mariana Alcantara",
    contexto: "Papelaria para cirurgia plástica — São Paulo",
    espec: "Cirurgia Plástica",
    servico: "Papelaria",
    praca: "São Paulo/SP",
    imagem: "/portfolio/marketing-medico-cirurgia-plastica-sao-paulo-papelaria.webp",
    largura: 1200,
    altura: 840,
    alt: "Papelaria impressa da Dra. Mariana Alcantara, cirurgia plástica em São Paulo",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2022/MM/sprint_4_MM_peca_grafica_papelaria/v3/mockup/Pasta/pasta_mockup.png",
  },
  {
    cliente: "Dr. Rodolpho Lemes – Ortopedia e Traumatologia",
    contexto: "Cartão virtual de endereço para ortopedista — Uruaçu",
    espec: "Ortopedia e Traumatologia",
    servico: "Cartão virtual",
    praca: "Uruaçu/GO",
    imagem: "/portfolio/marketing-medico-ortopedia-uruacu-cartao-virtual.webp",
    largura: 1200,
    altura: 982,
    alt: "Mockup de celular com o cartão virtual de endereço do Dr. Rodolpho Lemes, ortopedista em Uruaçu",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2025/RL/sprint_2_RL_cartao_virtual_endereco_u0/insumos/mockup_phone_RL_1.png",
  },
  {
    cliente: "Dr. Gilvan Furtado",
    contexto: "E-book para urologia e cirurgia robótica — Brasília",
    espec: "Urologia",
    servico: "E-book",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-urologia-brasilia-ebook-cirurgia-robotica.webp",
    largura: 1200,
    altura: 982,
    alt: "Mockup de celular com o e-book do Dr. Gilvan Furtado, urologia e cirurgia robótica em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Gilvan Furtado/2025/GV/sprint_3_GV_peca_grafica_ebook/insumos/mockup_phone_GV.png",
  },
  {
    cliente: "Dr. Bruno Lorenção",
    contexto: "Cartão virtual para medicina vascular — Brasília",
    espec: "Angiologia e Vascular",
    servico: "Cartão virtual",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-vascular-brasilia-cartao-virtual.webp",
    largura: 1200,
    altura: 982,
    alt: "Mockup de celular com o cartão virtual do Dr. Bruno Lorenção, medicina vascular em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Bruno Lorenção de Almeida/Design/2024/BL/sprint_1_BL_peca_grafica_cartao_virtual/insumos/mockup_phone.png",
  },
  {
    cliente: "Dra. Janina Huguenin",
    contexto: "Cartão virtual para cirurgia oncológica — Rio de Janeiro",
    espec: "Oncologia",
    servico: "Cartão virtual",
    praca: "Rio de Janeiro/RJ",
    imagem: "/portfolio/marketing-medico-oncologia-rio-de-janeiro-cartao-virtual.webp",
    largura: 1080,
    altura: 1080,
    alt: "Mockup de celular com o cartão virtual da Dra. Janina Huguenin, cirurgia oncológica no Rio de Janeiro",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2025/JH/sprint_4_JH_peca_grafica_cartao_virtual_u0/v1/Mockup_phone_JH.jpg",
  },
  {
    cliente: "Dra. Ana Cristina Medanha",
    contexto: "Site para clínica de medicina da dor — Araguaína",
    espec: "Medicina da Dor",
    servico: "Site",
    praca: "Araguaína/TO",
    imagem: "/portfolio/marketing-medico-medicina-da-dor-araguaina-site.webp",
    largura: 1200,
    altura: 500,
    alt: "Mockup de monitor com o site da Dra. Ana Cristina Medanha, medicina da dor em Araguaína",
    cartas: ["site-seo", "clinicas-e-consultorios"],
    origem: "/Clientes/2024/NA/sprint_3_NA_site_finalizacao/insumos/site_landing_mockup.jpg",
  },
  {
    cliente: "Dra. Daniela Machado",
    contexto: "Papelaria para dermatologia, estética e saúde capilar — Brasília",
    espec: "Dermatologia",
    servico: "Papelaria",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-dermatologia-brasilia-papelaria.webp",
    largura: 1200,
    altura: 900,
    alt: "Papel timbrado da Dra. Daniela Machado, dermatologia, estética e saúde capilar em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2025/DM/sprint_4_DM_peca_grafica_papelaria/insumos/Stationery_Mockup_3.jpg",
  },
  {
    cliente: "Hospital de Olhos do Distrito Federal",
    contexto: "Banner sobre prevenção de glaucoma para hospital de oftalmologia — Brasília",
    espec: "Oftalmologia",
    servico: "Banner",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-hospital-oftalmologia-brasilia-banner-glaucoma.webp",
    largura: 1200,
    altura: 933,
    alt: "Banner do Hospital de Olhos do Distrito Federal sobre prevenção de glaucoma",
    cartas: ["rede-hospitalar", "clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/HODF - Hospital de Olhos do Distrito Federal/Insumos/Design/2023/HO/sprint_1_HO_peca_grafica_banner_u0/insumos/banner mockup2.png",
  },
  {
    cliente: "Examine Agora – Imagem e Medicina",
    contexto: "Site para clínica de diagnóstico por imagem — Brasília",
    espec: "Diagnóstico por Imagem",
    servico: "Site",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-clinica-diagnostico-imagem-brasilia-site.webp",
    largura: 1200,
    altura: 500,
    alt: "Mockup de monitor com o site da Examine Agora, clínica de diagnóstico por imagem em Brasília",
    cartas: ["site-seo", "clinicas-e-consultorios"],
    origem: "/Clientes/2024/EA/sprint_6_EA_site_landing/insumos/site_landing_mockup.jpg",
  },
  {
    cliente: "Dr. Fernando Ferro",
    contexto: "E-book sobre artroplastia total de quadril para ortopedia — Goiânia",
    espec: "Ortopedia e Traumatologia",
    servico: "E-book",
    praca: "Goiânia/GO",
    imagem: "/portfolio/marketing-medico-ortopedia-goiania-ebook-artroplastia-quadril.webp",
    largura: 1200,
    altura: 982,
    alt: "Mockup de celular com o e-book do Dr. Fernando Ferro sobre artroplastia total de quadril",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2025/FF/sprint_2_FF_peca_grafica_ebook_u0/insumos/mockup_phone_FF.png",
  },
  {
    cliente: "Dr. Homero Ribeiro",
    contexto: "Folder sobre andrologia e medicina sexual masculina — Brasília",
    espec: "Urologia",
    servico: "Folder educativo",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-urologia-brasilia-folder-andrologia.webp",
    largura: 1200,
    altura: 900,
    alt: "Folder impresso do Dr. Homero Ribeiro sobre andrologia e medicina sexual masculina",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2025/HR/sprint_10_HR_peca_grafica_folder/insumos/Free_Folded_A5_Flyer_Mockup_3.png",
  },
  {
    cliente: "Clínica Renovare – Urologia e Andrologia",
    contexto: "Banner de Novembro Azul para clínica de urologia e andrologia — Brasília",
    espec: "Urologia",
    servico: "Banner",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-urologia-brasilia-banner-novembro-azul.webp",
    largura: 1200,
    altura: 1000,
    alt: "Banner da Clínica Renovare para a campanha de Novembro Azul, urologia e andrologia em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/_clientes_inativos/Clínica Renovare/2021/sprint_14_RN_campanha_novembro_azul/v1/apres/Banner/Mockup_Banner.png",
  },
  {
    cliente: "Incordis",
    contexto: "Cartão virtual para clínica de cardiologia e cirurgia vascular — Brasília",
    espec: "Cardiologia",
    servico: "Cartão virtual",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-cardiologia-brasilia-cartao-virtual.webp",
    largura: 1200,
    altura: 982,
    alt: "Mockup de celular com o cartão virtual da Incordis, cardiologia e cirurgia vascular em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2025/IN/sprint_1_IN_peca_grafica_cartao_virtual_u0/insumos/mockup_phone_IN.png",
  },
  // Fatia 2 das páginas de especialidade (2026-08-13) — busca do conector Dropbox
  // (§16.6-2), uma peça por página pra cruzar as 4 e destravar o índice.
  {
    cliente: "Clínica Inspire",
    contexto: "Portfólio impresso para clínica de otorrinolaringologia e cirurgia de cabeça e pescoço — Brasília",
    espec: "Otorrinolaringologia",
    servico: "Portfólio impresso",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-otorrinolaringologia-brasilia-portfolio-impresso.webp",
    largura: 1200,
    altura: 874,
    alt: "Folder trifold impresso da Clínica Inspire, otorrinolaringologia e cirurgia de cabeça e pescoço em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem:
      "/Clientes/_clientes_inativos/Clínica Inspire/Insumos/Design/2024/IS/sprint_2_IS_peca_grafica_portfolio/v1/apres/Impresso/Portfólio impresso - Clínica Inspire - Otorrinolaringologia e Cirurgia de Cabeça e Pescoço.pdf",
  },
  {
    cliente: "Sense Ginecologia Ltda",
    contexto: "Portfólio impresso para clínica de ginecologia e obstetrícia — Brasília",
    espec: "Saúde da Mulher",
    servico: "Portfólio impresso",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-ginecologia-brasilia-portfolio-impresso.webp",
    largura: 1200,
    altura: 805,
    alt: "Folder trifold impresso da Sense Ginecologia, clínica de ginecologia e obstetrícia em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem:
      "/Clientes/_clientes_inativos/Sense Ginecologia/2022/SG/sprint_15_SG_peca_grafica_portfolio/insumos/sprint_15_SG_peca_grafica_portfolio_Prancheta 1.png",
  },
  {
    cliente: "Clínica de Veias",
    contexto: "Anúncio A3 sobre saúde vascular para clínica de angiologia e cirurgia vascular — Brasília",
    espec: "Angiologia e Vascular",
    servico: "Anúncio",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-vascular-brasilia-anuncio.webp",
    largura: 867,
    altura: 1200,
    alt: "Anúncio A3 da Clínica de Veias sobre saúde vascular, angiologia e cirurgia vascular em Brasília",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2023/CV/sprint_12_CV_peca_grafica_anuncio_a3_u0/v2/apres/Anúncio - Clínica de Veias A3.pdf",
  },
  // Rodada 3 (2026-08-15) — caça página-orientada do §16.8-8: alvos Nefrologia (seca,
  // ver mapa) · Gastroenterologia · Ortopedia (completa em 7). Atribuição pela ARTE.
  {
    cliente: "IMED",
    contexto: "Marca aplicada em sinalização de ambiente para clínica de gastroenterologia — Brasília",
    espec: "Gastroenterologia",
    servico: "Sinalização",
    praca: "Brasília/DF",
    imagem: "/portfolio/marketing-medico-gastroenterologia-brasilia-sinalizacao-marca.webp",
    largura: 1200,
    altura: 675,
    alt: "Logo do IMED aplicado em sinalização de parede de ambiente, ao lado dos painéis de cor da identidade da clínica",
    cartas: ["clinicas-e-consultorios"],
    origem:
      "/Clientes/_clientes_inativos/Imed - Endoscopia e Colonoscopia/2023/ED/sprint_16_ED_criacao_logo_u0/1 - propostas/v1/Apres/sprint_16_ED_criacao_logo_u0_2.png",
  },
  {
    cliente: "Dr. Fernando Ferro",
    contexto: "Cartão virtual para ortopedista especializado em quadril — Goiânia",
    espec: "Ortopedia e Traumatologia",
    servico: "Cartão virtual",
    praca: "Goiânia/GO",
    imagem: "/portfolio/marketing-medico-ortopedia-goiania-cartao-virtual-quadril.webp",
    largura: 976,
    altura: 1200,
    alt: "Mockup de celular com o cartão virtual do Dr. Fernando Ferro, ortopedista especializado em quadril em Goiânia",
    cartas: ["clinicas-e-consultorios"],
    origem: "/Clientes/2024/FF/sprint_11_FF_peca_grafica_cartao_virtual/insumos/7fc616f24c9.png",
  },
];

/** Peças de uma carta, na ordem do registry. */
export const pecasDaCarta = (slug: string) => PORTFOLIO.filter((p) => p.cartas.includes(slug));
